/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package programa8;

/**
 *
 * @author Juan Carlos
 */
public class Programa8 extends javax.swing.JFrame {

    /**
     * Creates new form Programa8
     */
    public Programa8() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtnom = new javax.swing.JTextField();
        BtnMayus = new javax.swing.JButton();
        BtnMinus = new javax.swing.JButton();
        Btnlen = new javax.swing.JButton();
        txtres = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BtnMayus.setText("A mayusculas");
        BtnMayus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMayusActionPerformed(evt);
            }
        });

        BtnMinus.setText("A minusculas");
        BtnMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMinusActionPerformed(evt);
            }
        });

        Btnlen.setText("Longitud");
        Btnlen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnlenActionPerformed(evt);
            }
        });

        txtres.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtresKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtresKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(BtnMayus)
                .addGap(33, 33, 33)
                .addComponent(BtnMinus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(Btnlen)
                .addGap(41, 41, 41))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(txtnom, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(txtres, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(txtnom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnMayus)
                    .addComponent(BtnMinus)
                    .addComponent(Btnlen))
                .addGap(61, 61, 61)
                .addComponent(txtres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(87, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtresKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtresKeyPressed
        
    }//GEN-LAST:event_txtresKeyPressed

    private void txtresKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtresKeyTyped
        char txt = evt.getKeyChar();
        
        if(Character.isLetter(txt) || Character.isDigit(txt) || txt == ' ')
        {
            evt.consume();
        }
    }//GEN-LAST:event_txtresKeyTyped

    private void BtnMayusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMayusActionPerformed
        String cad = txtnom.getText();
        for (int i = 0; i < cad.length(); i++) {
            cad = cad.toUpperCase();
        }
        txtres.setText(cad);
    }//GEN-LAST:event_BtnMayusActionPerformed

    private void BtnMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMinusActionPerformed
        String cad = txtnom.getText();
        for (int i = 0; i < cad.length(); i++) {
            cad = cad.toLowerCase();
        }
        txtres.setText(cad);
    }//GEN-LAST:event_BtnMinusActionPerformed

    
    private void BtnlenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnlenActionPerformed
        String cad = txtnom.getText();
        txtres.setText(String.valueOf(metodochido(cad)));
    }//GEN-LAST:event_BtnlenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Programa8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Programa8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Programa8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Programa8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Programa8().setVisible(true);
            }
        });
    }
    
    public int metodochido(String cad)
    {
        int cont = 0;
        for (int i = 0; i < cad.length(); i++) {
            if(cad.charAt(i) == ' ')
            {
                cont++;
            }
        }
        return cad.length()-cont;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnMayus;
    private javax.swing.JButton BtnMinus;
    private javax.swing.JButton Btnlen;
    private javax.swing.JTextField txtnom;
    private javax.swing.JTextField txtres;
    // End of variables declaration//GEN-END:variables
}
