/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package programa3;

import javax.swing.DefaultListModel;

/**
 *
 * @author Juan Carlos
 */
public class Programa3 extends javax.swing.JFrame {
    
    DefaultListModel modelolista;
    DefaultListModel modelolista2;
    
    public Programa3() {
        initComponents();
        setLocationRelativeTo(null);
        modelolista = new DefaultListModel();
        modelolista2 = new DefaultListModel();
        Lista1.setModel(modelolista);
        Lista2.setModel(modelolista2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtelemento = new javax.swing.JTextField();
        lblelemento = new javax.swing.JLabel();
        btnagg = new javax.swing.JToggleButton();
        btnaderecha = new javax.swing.JToggleButton();
        btnaizquierda = new javax.swing.JToggleButton();
        btndelete = new javax.swing.JToggleButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        Lista1 = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        Lista2 = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblelemento.setText("Elementos:");

        btnagg.setText("Agregrar");
        btnagg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaggActionPerformed(evt);
            }
        });

        btnaderecha.setText("Derecha");
        btnaderecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaderechaActionPerformed(evt);
            }
        });

        btnaizquierda.setText("Izquierda");
        btnaizquierda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaizquierdaActionPerformed(evt);
            }
        });

        btndelete.setText("Eliminar");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });

        jScrollPane3.setViewportView(Lista1);

        jScrollPane4.setViewportView(Lista2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtelemento)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnagg)
                            .addComponent(btnaderecha)
                            .addComponent(btnaizquierda))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btndelete)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblelemento)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(lblelemento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtelemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnagg)
                    .addComponent(btndelete))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(btnaderecha)
                        .addGap(18, 18, 18)
                        .addComponent(btnaizquierda)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
                            .addComponent(jScrollPane3))
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnaggActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaggActionPerformed
        agregar();
        txtelemento.setText("");
    }//GEN-LAST:event_btnaggActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        int pos = Lista1.getSelectedIndex();
        if(Lista1.isSelectedIndex(pos))
        {
            eliminar();
        }
        else
        {
            eliminar2();
        }
    }//GEN-LAST:event_btndeleteActionPerformed

    private void btnaderechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaderechaActionPerformed
        derecha();
    }//GEN-LAST:event_btnaderechaActionPerformed

    private void btnaizquierdaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaizquierdaActionPerformed
        izquierda();
    }//GEN-LAST:event_btnaizquierdaActionPerformed
    
    public void derecha()
    {
        String cad = Lista1.getSelectedValue();
        try
        {
            int value = Lista1.getSelectedIndex();
            modelolista2.addElement(cad);
            Lista2.setModel(modelolista2);
            if(modelolista.getSize()!=0)
            {
                modelolista.removeElementAt(value);
            }
            Lista1.setModel(modelolista);
        }catch(Exception e)
        {
            
        }
    }
    
    public void izquierda()
    {
        String cad = Lista2.getSelectedValue();
        try
        {
            int value = Lista2.getSelectedIndex();
            modelolista.addElement(cad);
            Lista1.setModel(modelolista);
            if(modelolista2.getSize()!=0)
            {
                modelolista2.removeElementAt(value);
            }
            Lista2.setModel(modelolista2);
        }catch(Exception e)
        {
            
        }
    }
    
    public void agregar()
    {
        String cad = txtelemento.getText();
        modelolista.addElement(cad);
    }
    public void eliminar()
    {
        try
        {
            int pos = Lista1.getSelectedIndex();
            modelolista.remove(pos);
        }catch(Exception e)
        {
            
        }
    }
    public void eliminar2()
    {
        try
        {
            int pos = Lista2.getSelectedIndex();
            modelolista2.remove(pos);
        }catch(Exception e)
        {
            
        }
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Programa3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Programa3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Programa3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Programa3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Programa3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> Lista1;
    private javax.swing.JList<String> Lista2;
    private javax.swing.JToggleButton btnaderecha;
    private javax.swing.JToggleButton btnagg;
    private javax.swing.JToggleButton btnaizquierda;
    private javax.swing.JToggleButton btndelete;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblelemento;
    private javax.swing.JTextField txtelemento;
    // End of variables declaration//GEN-END:variables
}
